import Head from "next/head";

import PlayArea from "../components/PlayArea";
import Score from "../components/Score";
import StartScreen from "../components/StartScreen";
import GameOverScreen from "../components/GameOverScreen";
import Editor from "../components/Editor";

// Context
import { GameProvider } from "../contexts/GameContext";

export default function Home() {


  return (
    <>
      <Head>
        <title>Wack-a-mole</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={MainContainer}>  
        <GameProvider>

          <section style={PlayAreaStyle}>
            <StartScreen />
            <GameOverScreen />
            <Score />
            <PlayArea />
          </section>

          <section style={EditorAreaStyle}>
            <Editor />
          </section>

        </GameProvider>
      </main>

    </>
  );
}

const MainContainer: React.CSSProperties = {
  fontFamily: 'Arial, sans-serif',
  flex: 1,
  gap: "40px",
  display: "flex",
  flexWrap: "wrap",
  justifyContent: "center",
  alignItems: "flex-start",
  backgroundColor: "#E9EAEE",
  minHeight: "100vh",
  padding: "10vh 0"
};

const PlayAreaStyle: React.CSSProperties = {
  position: "relative",
  width: "100%",
  maxWidth: "400px",
  display: "flex",
  flexDirection: "column",
  justifyContent: "center",
  alignItems: "center",
  backgroundColor: "#FFFFFF",
};

const EditorAreaStyle: React.CSSProperties = {
  position: "relative",
  width: "100%",
  maxWidth: "450px",
  minHeight: "50vh",
  display: "flex",
  flexDirection: "column",
};