import Head from "next/head";
import { useContext, useEffect } from "react";

import PlayArea from "./components/PlayArea";
import Score from "./components/Score";
import StartScreen from "./components/StartScreen";
import GameOverScreen from "./components/GameOverScreen";

// Context
import { GameProvider } from "./contexts/GameContext";

export default function Home() {


  return (
    <>
      <Head>
        <title>Wack-a-mole</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={MainContainer}>  
        <GameProvider>
          <section style={PlayAreaStyle}>
            <StartScreen />
            <GameOverScreen />
            <Score />
            <PlayArea />
          </section>
        </GameProvider>
      </main>
    </>
  );
}

const MainContainer: React.CSSProperties = {
  flex: 1,
  display: "flex",
  justifyContent: "center",
  alignItems: "center",
  backgroundColor: "#E9EAEE",
  height: "100vh",
};

const PlayAreaStyle: React.CSSProperties = {
  paddingTop: "3vh",
  paddingBottom: "5px",
  width: "100%",
  maxWidth: "450px",
  display: "flex",
  flexDirection: "column",
  justifyContent: "center",
  alignItems: "center",
  margin: "auto",
  backgroundColor: "#FFFFFF",
};